"""
Snakefile for running fastsimcoal26 on stdpopsim data
Two population analysis
"""

import numpy as np
import stdpopsim
import fastsimcoal
import dadi_utils
import tskit
import pandas as pd
import plots

#from shutil import copyfile
#import pathlib
#import sys
###from stdpopsim import models

# ###############################################################################
# preperation :
# ###############################################################################

configfile: config["config"]+"/config.json"

np.random.seed(config["seed"])

# This is the number of samples to simulate for within each population
# for each replicate
# needs to be equal across sampled populations (or 0)
num_samples_per_population = config["num_samples_per_population"]
num_sampled_genomes_per_replicate = max(num_samples_per_population)

# The number of replicates of each analysis you would like to run
replicates = config["replicates"]

# Where you would like all output files from analysis to live
output_dir = config["config"]

# The analysis species
species = stdpopsim.get_species(config["species"])

# The specific model you would like to run
model = species.get_demographic_model(config["model"])

# The genetic map you would like to use.
# if value None is given default_recombination_rates are
# used with a flat map
genetic_map_id = config.get("genetic_map", None)

# The names of all chromosomes to simulate, separated by commas
# Use "all" to simulate all chromsomes for the genome
chrm_list = [chrom for chrom in species.genome.chromosomes]
if "chrY" in chrm_list:
    chrm_list.remove("chrY")
if(config["chrm_list"] != "all"):
    chrm_list = [chr for chr in config["chrm_list"].split(",")]
	
# The model for inference with fsc
# Need different priors and mutation rates depending on species
fsc_model = ['IM_hum']

# This grabs the default mr from the first chromosome,
# Ultimitely This needs to be replaced with the weighted average
# of all chromosomes: This should be done in stdpopsim.
mutation_rate = species.genome.mean_mutation_rate

# For plotting.
generation_time = model.generation_time

# ###############################################################################
# GENERAL RULES & GLOBALS
# ###############################################################################

seed_array = np.random.random_integers(1,2**31,replicates)

genetic_map_downloaded_flag= ".genetic_map_downloaded"

try:
    mask_file = config["mask_file"]
except KeyError:
    mask_file = None

rule all:
	input: output_dir + "/Results/estimates_N_tdiv_fsc.png", output_dir + "/Results/estimates_mig_fsc.png"

rule download_genetic_map:
    output: genetic_map_downloaded_flag
    message: "Downloading default genetic map"
    run:
        # We need to have this here to avoid several threads trying to download the
        # the genetic map into the cache at the same time.
        if genetic_map_id is not None:
            genetic_map = species.get_genetic_map(genetic_map_id)
            if not genetic_map.is_cached():
                genetic_map.download()
            with open(output[0], "w") as f:
                print("File to indicate genetic map has been downloaded", file=f)


rule simulation:
    input:
        genetic_map_downloaded_flag
    output:
        output_dir + "/Intermediate/{seeds}/{chrms}.trees"
    run:
        engine = stdpopsim.get_default_engine()
        contig = species.get_contig(wildcards.chrms, genetic_map=genetic_map_id)
        samples = model.get_samples(*num_samples_per_population)
        ts = engine.simulate(model, contig, samples, seed=wildcards.seeds)
        ts.dump(output[0])


# ###############################################################################
# dadi - prep for fsc
# ###############################################################################

rule ts_to_dadi_sfs:
    input:rules.simulation.output
    output: output_dir + "/Intermediate/{seeds}/{chrms}_dadi_joint_sfs.fs",
            output_dir + "/Intermediate/{seeds}/{chrms}_dadi_joint_sfs_with_nonvariant.fs"
    run:
        dadi_utils.ts_to_dadi_sfs(input[0], output[0],output[1], sample_size = num_sampled_genomes_per_replicate, mask_file=mask_file)

# ###############################################################################
# fastsimcoal
# ###############################################################################

rule dadi_sfs_to_fsc:
    input: expand(output_dir + "/Intermediate/{seeds}/{chrms}_dadi_joint_sfs_with_nonvariant.fs", chrms=chrm_list,seeds=seed_array)

    output: output_dir + "/Intermediate/{seeds}/fsc_analysis/{demo_model}_jointDAFpop1_0.obs"

    run:
        inputs = expand(output_dir + "/Intermediate/{seeds}/{chrms}_dadi_joint_sfs_with_nonvariant.fs", chrms=chrm_list,seeds=wildcards.seeds)
        dadi_out_path = output_dir + "/Intermediate/" + wildcards.seeds + "/all_chrm_dadi_joint_sfs_with_nonvariant.fs"
        fsc_out_path  = output_dir + "/Intermediate/" + wildcards.seeds + "/fsc_analysis/"+wildcards.demo_model+"_jointDAFpop1_0.obs"
        fastsimcoal.dadi_to_fsc_sfs(inputs, dadi_out_path, fsc_out_path, sample_size=num_sampled_genomes_per_replicate)


rule fsc_setup:
    input: expand(output_dir + "/Intermediate/{seeds}/fsc_analysis/{demo_model}_jointDAFpop1_0.obs", seeds=seed_array,demo_model=fsc_model)

    output: output_dir + "/Intermediate/{seeds}/fsc_analysis/{demo_model}.est",
            output_dir + "/Intermediate/{seeds}/fsc_analysis/{demo_model}.tpl"

    shell: "cp fsc_files/{wildcards.demo_model}.est {output_dir}/Intermediate/{wildcards.seeds}/fsc_analysis/{wildcards.demo_model}.est && \
            cp fsc_files/{wildcards.demo_model}.tpl {output_dir}/Intermediate/{wildcards.seeds}/fsc_analysis/{wildcards.demo_model}.tpl && \
            sed -i.bak 's/SAMPLE_SIZE/{num_sampled_genomes_per_replicate}/' {output_dir}/Intermediate/{wildcards.seeds}/fsc_analysis/{wildcards.demo_model}.tpl && rm {output_dir}/Intermediate/{wildcards.seeds}/fsc_analysis/{wildcards.demo_model}.tpl.bak &&\
            cd fsc26/ && chmod +x fsc26"

rule run_fsc:
    input: expand(output_dir + "/Intermediate/{seeds}/fsc_analysis/{demo_model}.tpl", seeds=seed_array,demo_model=fsc_model)

    output: output_dir + "/Intermediate/{seeds}/fsc_analysis/run10/{demo_model}/{demo_model}.bestlhoods"

    # I want to run this with a bash loop from 1..fit_runs to automate the number of fsc runs but for the life of me I cant get it to work in snakemake (it works fine in a shell script)
    # it keeps spitting out a python 'out of index' error and I've spent way too much time trying to troubleshoot it with no success
    # if someome can figure this out they would be my hero. Until that day, will continue to use this wall of bash code
    shell: "cd {output_dir}/Intermediate/{wildcards.seeds}/fsc_analysis/  && \
              mkdir run1 &&\
              cd run1 &&\
              cp ../{wildcards.demo_model}* ./ &&\
              ../../../../../fsc26/fsc26 fsc26 -t {wildcards.demo_model}.tpl -n 100000 -d -e {wildcards.demo_model}.est -M -L 40 -q -c 4 &&\
              cd .. &&\
              mkdir run2 &&\
              cd run2 &&\
              cp ../{wildcards.demo_model}* ./ &&\
              ../../../../../fsc26/fsc26 fsc26 -t {wildcards.demo_model}.tpl -n 100000 -d -e {wildcards.demo_model}.est -M -L 40 -q -c 4 &&\
              cd .. &&\
              mkdir run3 &&\
              cd run3 &&\
              cp ../{wildcards.demo_model}* ./ &&\
              ../../../../../fsc26/fsc26 fsc26 -t {wildcards.demo_model}.tpl -n 100000 -d -e {wildcards.demo_model}.est -M -L 40 -q -c 4 &&\
              cd .. &&\
              mkdir run4 &&\
              cd run4 &&\
              cp ../{wildcards.demo_model}* ./ &&\
              ../../../../../fsc26/fsc26 fsc26 -t {wildcards.demo_model}.tpl -n 100000 -d -e {wildcards.demo_model}.est -M -L 40 -q -c 4 &&\
              cd .. &&\
              mkdir run5 &&\
              cd run5 &&\
              cp ../{wildcards.demo_model}* ./ &&\
              ../../../../../fsc26/fsc26 fsc26 -t {wildcards.demo_model}.tpl -n 100000 -d -e {wildcards.demo_model}.est -M -L 40 -q -c 4 &&\
              cd .. &&\
              mkdir run6 &&\
              cd run6 &&\
              cp ../{wildcards.demo_model}* ./ &&\
              ../../../../../fsc26/fsc26 fsc26 -t {wildcards.demo_model}.tpl -n 100000 -d -e {wildcards.demo_model}.est -M -L 40 -q -c 4 &&\
              cd .. &&\
              mkdir run7 &&\
              cd run7 &&\
              cp ../{wildcards.demo_model}* ./ &&\
              ../../../../../fsc26/fsc26 fsc26 -t {wildcards.demo_model}.tpl -n 100000 -d -e {wildcards.demo_model}.est -M -L 40 -q -c 4 &&\
              cd .. &&\
              mkdir run8 &&\
              cd run8 &&\
              cp ../{wildcards.demo_model}* ./ &&\
              ../../../../../fsc26/fsc26 fsc26 -t {wildcards.demo_model}.tpl -n 100000 -d -e {wildcards.demo_model}.est -M -L 40 -q -c 4 &&\
              cd .. &&\
              mkdir run9 &&\
              cd run9 &&\
              cp ../{wildcards.demo_model}* ./ &&\
              ../../../../../fsc26/fsc26 fsc26 -t {wildcards.demo_model}.tpl -n 100000 -d -e {wildcards.demo_model}.est -M -L 40 -q -c 4 &&\
              cd .. &&\
              cd run10 &&\
              cp ../{wildcards.demo_model}* ./ &&\
              ../../../../../fsc26/fsc26 fsc26 -t {wildcards.demo_model}.tpl -n 100000 -d -e {wildcards.demo_model}.est -M -L 40 -q -c 4"

# ###############################################################################
# Compile results and plot
# ###############################################################################

rule get_fsc_output:
    input: expand(output_dir +  "/Intermediate/{seeds}/fsc_analysis/run10/{demo_model}/{demo_model}.bestlhoods",seeds=seed_array,demo_model=fsc_model)

    output: output_dir+"/Intermediate/{seeds}/fsc_analysis/fsc_results_sorted.txt"

    run:
        for seed in seed_array:
            fastsimcoal.get_fsc_output(output_dir+"/Intermediate/"+str(seed)+"/fsc_analysis/",10,"fsc_results_sorted.txt",fsc_model[0])

# see what it does
rule get_best_fsc_runs:
    input: expand(output_dir+"/Intermediate/{seeds}/fsc_analysis/fsc_results_sorted.txt", seeds=seed_array),

    output: output_dir + "/Results/best_fsc_runs.txt"

    run:
        fastsimcoal.get_best_fsc_runs(output_dir+"/Intermediate", seed_array, output[0])   

rule plot_estimates:
    input: rules.get_best_fsc_runs.output

    output: output_dir + "/Results/estimates_N_tdiv_fsc.png", output_dir + "/Results/estimates_mig_fsc.png"

    run:

        simulated_genome_length = 0
        for chr in chrm_list:
            ts=tskit.load(output_dir+"/Intermediate/"+str(seed_array[0])+"/"+chr+".trees")
            simulated_genome_length += ts.sequence_length
            if mask_file:
                mask_table = pd.read_csv(mask_file, sep="\t", header=None)
                sub = mask_table[mask_table[0] == chr]
                mask_ints = pd.IntervalIndex.from_arrays(sub[1], sub[2])
                simulated_genome_length -= np.sum(mask_ints.length)
        plots.plot_fsc_results_human_IM(input[0], output, simulated_genome_length)

rule clean:
    shell:
        f"rm -rf {output_dir}/Intermediate \
            {output_dir}/Results \
            .genetic_map_downloaded \
            .snakemake"		
		
		
		