name: popsim_env_test
channels:
  - conda-forge
  - bioconda
  - terhorst
dependencies:
  - python=3.7
  - pip:
    - stdpopsim
  - bioconda:dadi
  - bioconda:pysam
  - terhorst:smcpp
  - msprime
  - scikit-allel
  - snakemake
  - setuptools
  - matplotlib
  - pandas=0.24.2
  - tqdm
  - seaborn
  - pysam
  - htslib
  - ldc
  - scipy
  - attrs
  - cython
  - h5py
